import { defineDeepArea } from './deepStudyCatalogHelpers';

const HE = { phase2HA: true };

/** Fase 2H-E — Medicina nuclear, Dosimetria, Proteção radiológica */
export const PHASE_2HE_HEALTH_RADIATION = {
  medicina_nuclear: defineDeepArea({
    label: 'Medicina nuclear',
    aliases: [
      'medicina_nuclear',
      'nuclear_medicine',
      'radiofarmacos',
      'radiofarmacia',
    ],
    description:
      'Radiofármacos, imagem funcional (PET/SPECT), terapia radionuclídica e dosimetria interna — ponte entre física nuclear, radioquímica e biotecnologia.',
    formationGoal:
      'Radionuclídeos e detecção → IC em biodistribuição ou imagem → mestrado em dosimetria personalizada, teranóstica ou reconstrução avançada.',
    prerequisites: {
      math: [
        'Cálculo',
        'Probabilidade e estatística',
        'Álgebra linear',
        'Análise de sinais intro',
      ],
      physics: [
        'Física nuclear intro',
        'Interação radiação-matéria',
        'Detecção de radiação',
      ],
      chemistry: [
        'Bioquímica',
        'Radioquímica intro',
        'Química orgânica',
      ],
      computation: [
        'Python',
        'Processamento de imagem',
        'Jupyter',
        'Git',
      ],
    },
    theory: {
      foundations: [
        'Radioatividade aplicada à medicina',
        'Radionuclídeos médicos',
        'Meia-vida física, biológica e efetiva',
        'Radiofármacos',
        'Biodistribuição',
        'Traçadores',
        'Imagem funcional',
        'Detectores em medicina nuclear',
        'Gama-câmara',
        'PET',
        'SPECT',
        'Terapia radionuclídica',
        'Proteção do paciente',
        'Segurança ocupacional',
      ],
      intermediate: [
        'Produção de radioisótopos',
        'Geradores radioisotópicos',
        'Marcação radioativa',
        'Controle de qualidade de radiofármacos',
        'Cinética de biodistribuição',
        'Aquisição de imagens',
        'Reconstrução tomográfica',
        'Correção de atenuação',
        'Quantificação de imagem',
        'Dosimetria interna básica',
        'Protocolos clínicos',
        'Regulamentação e boas práticas',
      ],
      advanced: [
        'Farmacocinética de radiofármacos',
        'Teranóstica',
        'Terapia com radionuclídeos',
        'Dosimetria personalizada',
        'Modelagem de órgãos',
        'Segmentação de imagens',
        'Monte Carlo em medicina nuclear',
        'Reconstrução avançada',
        'Correções físicas em PET/SPECT',
        'Radiofármacos alvo-específicos',
        'Análise de incerteza',
        'IA para imagem nuclear',
      ],
      researchLevel: [
        'Dosimetria personalizada para terapia',
        'Novos radiofármacos',
        'Reconstrução de imagem com IA',
        'Quantificação absoluta em PET/SPECT',
        'Modelos biocinéticos',
        'Monte Carlo para dose em pacientes',
        'Teranóstica em oncologia',
        'Radiofármacos para neuroimagem',
        'Integração imagem-dados clínicos',
        'Validação de protocolos',
      ],
    },
    books: {
      introductory: [
        'Saha — Fundamentals of Nuclear Pharmacy',
        'Mettler & Guiberteau — Essentials of Nuclear Medicine Imaging',
      ],
      intermediate: [
        'Cherry, Sorenson & Phelps — Physics in Nuclear Medicine',
        'Bailey et al. — Nuclear Medicine Physics',
      ],
      advanced: ['IAEA — Nuclear Medicine Physics: A Handbook for Teachers and Students'],
      computational: [
        'Knoll — Radiation Detection and Measurement',
        'pydicom / ImageJ (referência)',
      ],
    },
    projectTracks: {
      basic: [
        'Cálculo de meia-vida efetiva',
        'Comparação de radionuclídeos médicos',
        'Gráfico de atividade administrada no tempo',
        'Mapa conceitual PET vs SPECT',
      ],
      intermediate: [
        'Modelo biocinético simplificado de dois compartimentos',
        'Simulação de decaimento de radiofármaco',
        'Cálculo de dose simplificada',
        'Análise de imagem sintética simples',
      ],
      advanced: [
        'Reconstrução tomográfica conceitual',
        'Simulação Monte Carlo simplificada de detecção',
        'Modelo de dosimetria personalizada',
        'Comparação de protocolos PET/SPECT',
      ],
      ictcc: [
        'Revisão de radiofármacos teranósticos',
        'Modelo computacional de biodistribuição',
        'Análise de qualidade de imagem nuclear',
        'Dosimetria simplificada para terapia',
      ],
      masters: [
        'Monte Carlo para dosimetria em medicina nuclear',
        'IA para reconstrução ou segmentação',
        'Dosimetria personalizada em terapia radionuclídica',
        'Modelos biocinéticos com incerteza',
      ],
    },
    professorQuestions: [
      'Medicina nuclear vs dosimetria: onde colocar projeto de dose?',
      'Dados clínicos reais são exigíveis em IC?',
      'Monte Carlo clínico é viável em graduação?',
      'Como conectar a química nuclear e biotecnologia?',
      'PET vs SPECT: qual modalidade priorizar no TCC?',
      'Regulação ANVISA/IAEA: profundidade mínima?',
      'IA em imagem: trilha própria ou subtópico?',
      'Teranóstica exige parceria hospitalar?',
    ],
  }, HE),

  dosimetria: defineDeepArea({
    label: 'Dosimetria',
    aliases: ['dosimetria', 'dosimetry', 'dose'],
    description:
      'Grandezas dosimétricas, dosímetros, calibração, Monte Carlo e metrologia — base quantitativa para medicina nuclear, radioterapia e proteção.',
    formationGoal:
      'Grandezas e atenuação → IC com MC ou fantoma → mestrado em dosimetria computacional, microdosimetria ou UQ.',
    prerequisites: {
      math: [
        'Probabilidade e estatística',
        'Cálculo',
        'Análise de erro',
        'Métodos numéricos intro',
      ],
      physics: [
        'Física nuclear',
        'Interação radiação-matéria',
        'Detecção',
      ],
      chemistry: ['Biofísica intro'],
      computation: [
        'Python',
        'Monte Carlo intro',
        'Visualização',
        'Git',
      ],
    },
    theory: {
      foundations: [
        'Grandezas dosimétricas',
        'Atividade',
        'Exposição',
        'Dose absorvida',
        'Dose equivalente',
        'Dose efetiva',
        'Kerma',
        'LET',
        'RBE',
        'Unidades radiológicas',
        'Fontes de radiação',
        'Interação radiação-matéria',
        'Atenuação',
        'Incerteza em medidas',
      ],
      intermediate: [
        'Equilíbrio de partículas carregadas',
        'Cavidade de Bragg-Gray',
        'Dosímetros',
        'Câmaras de ionização',
        'TLD',
        'OSL',
        'Filmes radiocrômicos',
        'Calibração',
        'Rastreabilidade',
        'Espectrometria',
        'Dosimetria externa',
        'Dosimetria interna',
        'Estatística de contagem',
      ],
      advanced: [
        'Microdosimetria',
        'Dosimetria em campos mistos',
        'Dosimetria de nêutrons',
        'Modelos antropomórficos',
        'Phantoms',
        'Monte Carlo para dose',
        'Transporte de partículas',
        'Incerteza dosimétrica',
        'Dosimetria em radioterapia',
        'Dosimetria em medicina nuclear',
        'Validação experimental',
        'Protocolos internacionais',
      ],
      researchLevel: [
        'Dosimetria personalizada',
        'Monte Carlo em geometrias realistas',
        'Dosimetria de pequenos campos',
        'Dosimetria de nêutrons',
        'Modelos voxelizados',
        'Microdosimetria computacional',
        'Calibração avançada',
        'Intercomparações',
        'UQ em dose',
        'Dados nucleares para dosimetria',
      ],
    },
    books: {
      introductory: [
        'Attix — Introduction to Radiological Physics and Radiation Dosimetry',
        'Knoll — Radiation Detection and Measurement',
      ],
      intermediate: [
        'Podgorsak — Radiation Physics for Medical Physicists',
        'Khan — The Physics of Radiation Therapy',
      ],
      advanced: ['ICRU Reports (seleção)', 'IAEA dosimetry technical reports'],
      computational: ['EGSnrc', 'MCNP dose tallies (referência)'],
    },
    projectTracks: {
      basic: [
        'Conversão entre grandezas radiológicas',
        'Cálculo de dose absorvida simplificada',
        'Curva de atenuação em material',
        'Comparação de unidades e limites',
      ],
      intermediate: [
        'Simulação de dose relativa por distância',
        'Modelo de dosímetro simples',
        'Análise de incerteza em medida radiológica',
        'Comparação de materiais para blindagem',
      ],
      advanced: [
        'Monte Carlo simplificado para deposição de energia',
        'Dose em geometria 2D simplificada',
        'Modelo de dosimetria interna',
        'Comparação entre protocolos de dose',
      ],
      ictcc: [
        'Estudo computacional de dosimetria em blindagem',
        'Análise de incerteza em dosimetria experimental',
        'Comparativo de dosímetros',
        'Modelo simplificado para dose em medicina nuclear',
      ],
      masters: [
        'Dosimetria Monte Carlo com geometrias realistas',
        'Microdosimetria computacional',
        'Dosimetria personalizada',
        'UQ avançada em dose',
      ],
    },
    professorQuestions: [
      'Dosimetria vs proteção radiológica: qual trilha para ALARA?',
      'MCNP é obrigatório ou Python didático basta?',
      'Fantomas voxel: escopo de IC?',
      'Como validar MC sem medida experimental?',
      'Ligação com trilha Monte Carlo (2H-B)?',
      'Dose interna: overlap com medicina nuclear?',
      'ICRU/IAEA: quantas normas citar?',
      'Incerteza GUM em graduação: nível exigido?',
    ],
  }, HE),

  protecao_radiologica: defineDeepArea({
    label: 'Proteção radiológica',
    aliases: [
      'protecao_radiologica',
      'radiological_protection',
      'radioprotecao',
      'seguranca_radiologica',
    ],
    description:
      'ALARA, blindagem, monitoração, emergências e cultura de segurança — para laboratórios, medicina nuclear, indústria e instalações nucleares.',
    formationGoal:
      'Princípios e limites → plano de proteção em IC → mestrado em otimização de blindagem, emergência ou análise probabilística de risco.',
    prerequisites: {
      math: [
        'Probabilidade',
        'Estatística',
        'Álgebra básica',
      ],
      physics: [
        'Radiação ionizante',
        'Interação radiação-matéria',
        'Física nuclear intro',
      ],
      chemistry: ['Rejeitos e química ambiental intro'],
      computation: [
        'Python',
        'Planilhas',
        'Simulação simples',
        'Documentação técnica',
      ],
    },
    theory: {
      foundations: [
        'Radiação ionizante',
        'Fontes naturais e artificiais',
        'Efeitos biológicos',
        'Princípios de proteção radiológica',
        'Tempo, distância e blindagem',
        'ALARA',
        'Limites de dose',
        'Classificação de áreas',
        'Monitoração individual',
        'Monitoração ambiental',
        'Sinalização',
        'Cultura de segurança',
        'Normas e regulamentação',
        'Rejeitos radioativos',
      ],
      intermediate: [
        'Avaliação de risco radiológico',
        'Planejamento de blindagem',
        'Cálculo de taxa de dose',
        'Levantamento radiométrico',
        'Procedimentos operacionais',
        'Emergência radiológica',
        'Transporte de material radioativo',
        'Controle de contaminação',
        'Descontaminação',
        'Licenciamento',
        'Proteção ocupacional',
        'Proteção do público',
        'Documentação e registros',
      ],
      advanced: [
        'Análise probabilística de segurança',
        'Termo fonte',
        'Dispersão ambiental',
        'Modelagem de acidentes',
        'Proteção em instalações nucleares',
        'Proteção em medicina nuclear',
        'Proteção em radioterapia',
        'Proteção em indústria',
        'Proteção contra nêutrons',
        'Otimização de blindagem',
        'Gestão de rejeitos',
        'Comunicação de risco',
      ],
      researchLevel: [
        'Modelos de dispersão radiológica',
        'Otimização de blindagem',
        'Análise de risco em instalações',
        'Cultura de segurança',
        'Resiliência em emergência',
        'Dosimetria ambiental',
        'Transporte e rejeitos',
        'Proteção em novas tecnologias nucleares',
        'Modelagem de cenários',
        'Tomada de decisão sob incerteza',
      ],
    },
    books: {
      introductory: [
        'Cember & Johnson — Introduction to Health Physics',
        'Turner — Atoms, Radiation, and Radiation Protection',
        'IAEA — Radiation Protection and Safety of Radiation Sources',
      ],
      intermediate: [
        'Shultis & Faw — Radiation Shielding',
        'Knoll — Radiation Detection and Measurement',
        'ICRP Publications (seleção)',
      ],
      advanced: ['Martin — Introduction to Radiation Protection'],
      computational: [
        'Códigos de blindagem / Python MC 1D',
        'Normas CNEN/IAEA (referência)',
      ],
    },
    projectTracks: {
      basic: [
        'Cálculo de redução de dose por distância',
        'Comparação de blindagens',
        'Mapa de sinalização radiológica',
        'Checklist de segurança radiológica',
      ],
      intermediate: [
        'Plano de proteção radiológica para laboratório didático',
        'Simulação de taxa de dose ao redor de fonte',
        'Análise de monitoração individual',
        'Matriz de risco radiológico',
      ],
      advanced: [
        'Otimização de blindagem',
        'Modelo de emergência radiológica',
        'Dispersão ambiental simplificada',
        'Análise de proteção em instalação médica',
      ],
      ictcc: [
        'Plano conceitual de proteção radiológica',
        'Análise de cultura de segurança',
        'Comparação de normas e práticas',
        'Estudo computacional de blindagem ocupacional',
      ],
      masters: [
        'Otimização multiobjetivo de proteção radiológica',
        'Modelagem de cenários de emergência',
        'Análise probabilística de risco radiológico',
        'Proteção radiológica em novas instalações nucleares',
      ],
    },
    professorQuestions: [
      'Proteção vs dosimetria: onde ensinar grandezas?',
      'CNEN vs ICRP: qual base priorizar no TCC?',
      'Simulação de acidente sem dados reais?',
      'Cultura de segurança: método qualitativo aceito?',
      'Conexão com engenharia nuclear na banca?',
      'Blindagem: MC ou fórmulas analíticas?',
      'Medicina nuclear: proteção do paciente ou trabalhador?',
      'Emergência radiológica: escopo ético em IC?',
    ],
  }, HE),
};
