-- ============================================================
-- Verifica se public.edital contém todas as colunas que o loader
-- pode enviar no upsert (EDITALFINDER_EXTENDED_SCHEMA=true).
--
-- Uso: executar no SQL editor; o resultado deve ser 0 linhas.
-- ============================================================

with expected (col) as (
  values
  ('acao'),
  ('access_reason'),
  ('access_status'),
  ('anexos'),
  ('area'),
  ('area_cientifica'),
  ('area_tecnologica'),
  ('ativo'),
  ('carencia'),
  ('chamada'),
  ('cidade'),
  ('classificacao_confianca'),
  ('codigo_oportunidade'),
  ('compatibilidade'),
  ('contato'),
  ('content_type_detectado'),
  ('contrapartida'),
  ('data_abertura'),
  ('data_encerramento'),
  ('data_publicacao'),
  ('data_resultado'),
  ('descricao'),
  ('descricao_en'),
  ('descricao_original'),
  ('descricao_traduzida'),
  ('documentos'),
  ('edital_numero'),
  ('elegibilidade'),
  ('estado'),
  ('extraction_mode'),
  ('extras'),
  ('finalidade_financiamento'),
  ('fonte_recurso'),
  ('garantias'),
  ('hash_deduplicacao'),
  ('id_organizacao'),
  ('idioma_original'),
  ('instituicao'),
  ('justificativa'),
  ('limite_financiavel'),
  ('linha_credito'),
  ('link'),
  ('link_inscricao'),
  ('modalidade_financiamento'),
  ('moeda'),
  ('motivo_rejeicao'),
  ('municipio'),
  ('natureza_recurso'),
  ('numero_chamada'),
  ('numero_edital'),
  ('numero_processo'),
  ('objetivo'),
  ('ods'),
  ('orgao'),
  ('orgao_contratante'),
  ('orgao_responsavel'),
  ('origem_portal'),
  ('pais'),
  ('pdf_resumo'),
  ('pdf_url'),
  ('percentual_financiavel'),
  ('perfil_ideal'),
  ('prazo_amortizacao'),
  ('prazo_carencia'),
  ('prazo_envio'),
  ('prazo_pagamento'),
  ('prazo_total'),
  ('programa'),
  ('publico_alvo'),
  ('publico_alvo_arr'),
  ('publico_beneficiario'),
  ('qualidade_dado'),
  ('recomendacao'),
  ('reembolsavel'),
  ('regiao'),
  ('score'),
  ('score_detalhado'),
  ('setor_economico'),
  ('setor_estrategico'),
  ('situacao'),
  ('subprograma'),
  ('suspeito'),
  ('tags'),
  ('taxa_juros'),
  ('temas'),
  ('tipo_oportunidade'),
  ('tipo_recurso'),
  ('titulo'),
  ('titulo_en'),
  ('titulo_original'),
  ('titulo_traduzido'),
  ('traducao_automatica'),
  ('uf'),
  ('ultima_coleta'),
  ('unidade_responsavel'),
  ('url_detalhe'),
  ('url_listagem'),
  ('validacao_status'),
  ('valor_estimado'),
  ('valor_maximo'),
  ('valor_minimo'),
  ('valor_total'),
  ('valor_total_texto'),
  ('warnings')
)
select e.col as coluna_em_falta_em_public_edital
from expected e
left join information_schema.columns c
  on c.table_schema = 'public'
 and c.table_name = 'edital'
 and c.column_name = e.col
where c.column_name is null
order by 1;
