/** Etiquetas curtas nas sidebars — valores cravados no banco (snake_kebab). */

export const TIPO_OPORTUNIDADE_OPTIONS = [
  { id: '', label: '(todos)' },
  { id: 'chamada_publica', label: 'Chamada pública' },
  { id: 'edital', label: 'Edital' },
  { id: 'financiamento', label: 'Financiamento' },
  { id: 'credito', label: 'Crédito' },
  { id: 'funding_opportunity', label: 'Funding opportunity' },
  { id: 'call_for_proposals', label: 'Call for proposals' },
  { id: 'innovation_programme', label: 'Programa de inovação' },
  { id: 'startup_programme', label: 'Programa startups' },
  { id: 'accelerator', label: 'Aceleradora' },
  { id: 'grant', label: 'Grant' },
  { id: 'licitacao', label: 'Licitação' },
  { id: 'procurement', label: 'Procurement' },
  { id: 'oportunidade_fornecedor', label: 'Oportunidade fornecedor' },
  { id: 'programa_inovacao', label: 'Programa inovação' },
  { id: 'project_financing', label: 'Projeto financiável' },
  { id: 'cooperacao_tecnica', label: 'Cooperação técnica' },
];

export const TIPO_RECURSO_OPTIONS = [
  'subvencao',
  'credito',
  'financiamento',
  'reembolsavel',
  'nao_reembolsavel',
  'grant',
  'fomento',
  'equity',
  'venture',
  'fundo_investimento',
  'apoio_inovacao',
  'apoio_tecnico',
  'oportunidade_fornecedor',
  'licitacao',
  'licitação',
  'apoio_internacionalizacao',
];

export const PERFIL_IDEAL_OPTIONS = [
  'startup',
  'empresa',
  'microempresa',
  'pequena_empresa',
  'media_empresa',
  'grande_empresa',
  'fornecedor',
  'pesquisador',
  'universidade',
  'ict',
  'produtor_rural',
  'cooperativa',
  'municipio',
  'governo',
  'consorcio',
];

export const SETOR_ESTRATEGICO_OPTIONS = [
  'inovacao',
  'inovação',
  'ciencia e tecnologia',
  'energia',
  'sustentabilidade',
  'clima',
  'industria',
  'indústria',
  'agro',
  'infraestrutura',
  'defesa',
  'nuclear',
  'aeroespacial',
  'saude',
  'saúde',
  'educacao',
  'educação',
  'digital',
  'cidades',
  'desenvolvimento regional',
];

export const AREA_TECNOLOGICA_OPTIONS = [
  'inteligencia artificial',
  'inteligência artificial',
  'computacao',
  'computação',
  'biotecnologia',
  'materiais',
  'energia',
  'agrobiotecnologia',
  'aeroespacial',
  'nuclear',
  'manufatura',
  'sensores',
  'robotica',
  'robótica',
  'seguranca',
  'segurança',
  'saude digital',
  'saúde digital',
];

export const REGIOES_BR = [
  'Nacional',
  'Sul',
  'Sudeste',
  'Nordeste',
  'Centro-Oeste',
  'Norte',
];

export const STATUS_PRESET_OPTIONS = [
  { id: 'aberto', label: 'Abertos (com prazo futuro)' },
  { id: 'encerrado', label: 'Encerrados / prazo vencido' },
  { id: 'sem_prazo', label: 'Sem prazo informado' },
  { id: 'ativo', label: 'Ativos (cadastro)' },
  { id: 'inativo', label: 'Inativos (cadastro)' },
  { id: 'validado', label: 'Validados' },
  { id: 'suspeito', label: 'Suspeitos (validação)' },
  { id: 'incompleto', label: 'Incompletos' },
  { id: 'acesso_limitado', label: 'Acesso limitado' },
];
